version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "25500-25600"
    volumes: 
      - ./minecraft_servers:/minecraft_servers
      #- ./app/config:/crafty-web/app/config